redwoodjs/create-redwood-app

web/src/index.js
web/src/pages/FatalErrorPage/FatalErrorPage.js

Capture fatal errors and show a user-customizable error page when encountered.
Requires https://github.com/redwoodjs/redwood/pull/61 to be merged into @redwoodjs/web first.

Add FatalErrorPage and friends

---

.gitignore
web/.babelrc.js
web/package.json

When using Babel with Webpack it is optimal to specify `modules: false` to Babel's `env` preset in order to **not** convert es6 import statements in `require`s. This is because Webpack both understands and relies on true import statements for tree-shaking.
This PR also adds a command to run JUST Babel on the web side, allowing for easier debugging and making sure it's doing what we expect.

Tooling for Babel debugging

---

api/package.json
package.json

This removes the postinstall script which creates the database, applies migrations and generates the Prisma client after packages are installed.
We're removing this to allow `yarn create redwood-app` to work without interrupting the user. We will use `prisma --watch` during development.

Remove postinstall db:up step.

---

api/package.json
api/src/functions/graphql.js
babel.config.js
package.json
yarn.lock

Here's what the "load all *.sdl.js" files approach looks like with import-all.macro. Pretty clean, and gets us static `require` statements that should work fine with ZiSi. I put it in the root-level `babel.config.js` since it seems reasonable to offer it on both web and api sides.
@peterp let me know if you like where this lives in `package.json` and friends.

Use importAll macro to load all schema/resolver files

---

netlify.toml

Tested and deployed on redwoodblog, looks good: https://hungry-hawking-c81bc6.netlify.com/contact (used to 404)

Add redirects to netlify.toml

---

redwood.toml

Dependent on redwoodjs/redwood/pull/101
New proposed config setting for opening browser on `yarn rw dev`

add browser.open config

---

README.md
README_APP.md

Dependent on redwoodjs/redwood/pull/154
Adds a README_APP, which is set as README.md at the time of installation.
Added content to both:
- README.md: for repo with contributing focused content
- README_APP.md: for local app dev with links and setup content

Split root READMEs for 1. Repo and 2. Local App Dev

---

yarn.lock

Fixes security warning:
https://github.com/redwoodjs/create-redwood-app/network/alert/yarn.lock/minimist/open
This was a manual update of yarn.lock. Went through some local tests to confirm before merging.

security: bump minimist v1.2.5 and v0.2.1

---

.editorconfig
.vscode/extensions.json

The EditorConfig further guarantees the coding standards that are being followed.
You still have more to check the files' charset.
More:
https://editorconfig.org/

Add editor config

---

.env
.env.defaults
api/prisma/schema.prisma

@peterp I noticed a couple of people saying they had to change binaryTargets to `["native", "windows"]` but I wonder if that's really necessary or if just `"native"` would work on its own. This PR assumes that just `"native"` is okay, can you test on your Window VM?
I'm going to update the tutorial once this goes into a real release to let users know they need to set the environment variable on Netlify to `"rhel-openssl-1.0.x"`.

Put binaryTargets in ENV var

---

web/package.json

This ensures that a new application has its `web/package.json` file in order (in terms of formatting and packages sorting), so that running `yarn workspace web add` produces changes only to the newly added packages’ lines.

Sort default packages order and format file

---

api/src/lib/db.js

at this time, no longer implementing this workaround to support PrismaClient lack of userId support

revert db.js foreignKeyReplacement workaround #50

---

redwood.toml

This PR adds some explanatory comments to the top of `redwood.toml`, the same kind of content you see in [.env.defaults](https://github.com/redwoodjs/create-redwood-app/blob/532495a39c7d1ba9ea36001ba8d0f8f6264c4f3e/.env.defaults#L1-L4). Via https://github.com/redwoodjs/redwoodjs.com/pull/173.

Add explanatory comment to redwood.toml

---

api/src/functions/graphql.js

Complementary PR to https://github.com/redwoodjs/redwood/pull/788, which removed the importAll.macro in favor of a babel plugin that lets us use more-regular import syntax. Relevant to the schema stitching happening in `graphql.js` (the serverless function).

Replace importAll with babel plugin

---

api/src/lib/db.js

The commented url to documentation in db.js was bad.
- Was `https://github.com/prisma/prisma2/blob/master/docs/prisma-client-js/api.md#constructor`
- replaced with `https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/constructor`

Update constructor doc link

---

.env.example

Adds an .env.example so that post-init clones/forks have a config example.

Add env example

---

.all-contributorsrc
README.md

This is the configuration required for https://github.com/redwoodjs/redwood/pull/875
Individual contributors will be displayed on the Framework repo README. Using a GitHub action, data will be pulled from this config file.
I've added a link to this repo README.me to the Framework README Contributors section.
**Do not merge until 875 is sorted.**

Add all-contributors file with populated data

---

.env.defaults

Related to work on Prisma Upgrade and pinning Prisma version. Currently, Prisma CLI will prompt user to update if a new version is available. We do not want this 'cause, you know, bad things:
https://github.com/redwoodjs/redwood/pull/841
Documentation from https://github.com/prisma/prisma/releases/tag/2.1.0

[Code Mod] Disable Prisma CLI update notifier

---

netlify.toml

`dataMigrate up` requires Prisma Client to be built, but we specifically do not build the client at build time. :(

Remove `dataMigrate up` from netlify.toml

---

api/prisma/seeds.js

Similar to issue [#982](https://github.com/redwoodjs/redwood/issues/982) this PR adds a $ dollar prefix to the prisma disconnect method which was depreciated in [Prisma 2.4](https://github.com/prisma/prisma/releases/tag/2.4.0)

add dollar prefix to prisma disconnect method

---

web/jsconfig.json

JSON standard does not allow trailing comma (RFC-7159)
Not essential for sure, but it appears as an error in IntelliJ, and possibly in various other IDE.

Typo, suppress trailing comma

---

api/prisma/schema.prisma

Prisma v2.9.0 fails on deploy unless we set `binaryTargets = ["native", "rhel-openssl-1.0.x"]` in schema.prisma.
No one from Prisma or Netlify can explain why. 
But they all assure me everything is fine.
¯\_(ツ)_/¯

(re)add rhel-openssl-1.0.x to schema.prisma

---

.env
.env.defaults

Currently it is a bit implicit that you can use the `TEST_DATABASE_URL`
env variable. I was able to figure this out by looking through the
source code, and since someone posted this on the issue tracker it means
more people find it a bit implicit.
Fixes: https://github.com/redwoodjs/redwood/issues/1620

Add TEST_DATABASE_URL to the default .env
